print("Hello World!")
nome = input("Dígite seu nome: ")
print(f"Olá, {nome}!")
valor1 = int(input("Digite um valor: "))
valor2 = int(input("Digite outro valor: "))
print(f"soma de {valor1} + {valor2} é: {valor1+valor2}")